_commit: 8b9c331
_src_path: git+git@codeberg.org:alekzandev/mlops-template.git
author: Alekzandev
email: aleksandev@proton.me
project_description: MLflow fundamentals for MLOps Engineering
project_name: mlflow-101
python_version: '3.10'
version: 0.1.0
